export const ORG_REQUEST = 'ORG_REQUEST';
export const ORG_SUCCESS = 'ORG_SUCCESS';
export const ORG_FAILURE = 'ORG_FAILURE';

export const CART_FETCH_REQUEST = 'CART_FETCH_REQUEST';
export const CART_FETCH_SUCCESS = 'CART_FETCH_SUCCESS';
export const CART_FETCH_FAILURE = 'CART_FETCH_FAILURE';

export const CART_ADD_REQUEST = 'CART_ADD_REQUEST';
export const CART_ADD_SUCCESS = 'CART_ADD_SUCCESS';
export const CART_ADD_FAILURE = 'CART_ADD_FAILURE';

export const CART_REMOVE_REQUEST = 'CART_REMOVE_REQUEST';
export const CART_REMOVE_SUCCESS = 'CART_REMOVE_SUCCESS';
export const CART_REMOVE_FAILURE = 'CART_REMOVE_FAILURE';

export const CART_CLEAR_REQUEST = 'CART_CLEAR_REQUEST';
export const CART_CLEAR_SUCCESS = 'CART_CLEAR_SUCCESS';
export const CART_CLEAR_FAILURE = 'CART_CLEAR_FAILURE';

export const SEARCH = 'SEARCH';
export const ADD_VOUCHER = 'ADD_VOUCHER';
export const REMOVE_VOUCHER = 'REMOVE_VOUCHER';
